spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          url: https://github.com/brainchen2020/SpringCloudConfig
          searchPaths: respo
          username:
          password:
      label: master
server:
  port: 8888
